# READ-ME: before anything, make sure your R work directory has the files 'CCApackage.R' and 'main_CCA.R' (it is assumed you know how to define a work directory in R)
# This script has 3 parts:
# parte 1) EXTERNAL SOURCE: here you will call functions necessary for running CCA (all necessary functions are in the file CCApackage.R)
# parte 2) PARAMETERS: here you will load your datasets (2 datasets) and set parameters for running your CCA
# parte 3) CCA: here you will actually run your CCA using your datasets and previously defined parameters
# The main function runCCA is in parte 3. It can be run in several modes:
# mode 1) Default mode: runCCA(publish = FALSE). It does not use any parameters defined by the user, instead it uses default parameters (not adequate for all analysis)
# mode 2) User defined mode: runCCA(list_param, publish = FALSE). It uses a list of parameters defined by the user in part 2 of this script
# mode 3) Publishing mode: runCCA(publish = TRUE) or runCCA(list_param, publish = TRUE). It creats a set of folders and files ready for publication (only use it after finding an awesome set of parameters for your CCA!)
# After runCCA, go look inside your work directory. A folder named output_CCA was created there. It includes all folders and files generated by your CCA.

# EXTERNAL SOURCE ---------------------------------------------------------------------------------------

# this will load all required functions for CCA
source("CCApackage.R")

# PARAMETERS --------------------------------------------------------------------------------------------

# use read.csv() to upload your datasets or use NA. If you choose NA, you will be directed to dynamically choose an Excel file containing 2 spreadsheets corresponding to data_X and data_Y
# warning: make sure your data sets use '.' (dot) as decimal separator and that all rows correspond to observations (individuals) and all columns to variables
# if you use data_X <- NA or data_Y <- NA, after running the function runCCA a pop-up window will appear for you to choose the appropriate Excel file (with at least two spreadsheets) in your computer, this file will be automatically put as part of the DATA PARAMETERS in the object 'list_param' below.
data_X <- read.table("/Users/otavio.cmarques/Documents/Otavio/DISCIPLINA POS/CCA 16-05/LENA DATA/CCA_CONTROLS chemotaxis cytokine genes.txt", header = TRUE, sep = "\t")
data_Y <- read.table("/Users/otavio.cmarques/Documents/Otavio/DISCIPLINA POS/CCA 16-05/LENA DATA/CCA_CONTROLS neutrophil genes.txt", header = TRUE, sep = "\t")

# this list of parameters will determine the behavior of the function runCCA (i.e. aspect of figures and numerical results of the CCA)
list_param <- list(
    # FIXED PARAMETERS
    empty = FALSE,                                                           # keep this parameter as FALSE
    # GENERIC PARAMETERS
    force_install_all_packages = FALSE,                                      # if packages do not load correctly, set this parameter to TRUE
    print_descriptive_statistics = TRUE,                                     # print out in the R console descriptive measures for each variable in 'data_X' and 'data_Y'  
    # REGULARIZED CCA (WHEN N OF VARIABLES GREATER THAN N OF OBSERVATIONS)
    rCCA_regularization = TRUE,                                             # rCCA: use TRUE if you selected more variables than you have observations in your datasets
    rCCA_n_points = 10,                                                      # rCCA: number of grid points used for searching the optimum regularization parameter lambda. more points can lead to a better approximation, but also to a substantially higher searching time for the algorithm
    # PLOT: HEATMAP OF PEARSON CORRELATIONS
    heatmap_clust_method = "ward.D2",                                        # Correlation plot: method for clustering correlation matrices (enter ?hclust in the R console for other allowed clustering methods)
    heatmap_color_ramp = RColorBrewer::brewer.pal(n = 7, name = "RdYlBu"),   # Correlation plot: gradient of colors for filling correlation matrix
    heatmap_border_color = grey(0.4),                                        # Correlation plot: color for borders of the correlation matrix
    heatmap_fontsize = 5,                                                    # Correlation plot: font size for the variables' names
    heatmap_width = 13,                                                      # Correlation plot: figure dimension: width
    heatmap_height = 7,                                                      # Correlation plot: figure dimension: height
    # PLOT: UNDIRECTED GRAPH OF PEARSON CORRELATIONS
    plotCorCCA_n_canonical_variates = 2,                                     # Correlation and CCA plots: number of canonical variates to plot (if greater than 2, it will override the parameter 'plots_canonical_variate' for the correlation graphs)
    plotCorCCA_corr_min = 0.7,                                               # Correlation and CCA plots: threshold determining the minimum correlation to be considered between variables
    plotCorCCA_seed = 10,                                                    # Correlation and CCA plots: choose any positive number whatsoever
    plotCorCCA_node_size = 5,                                                # Correlation and CCA plots: size of nodes drawn in the graph
    plotCorCCA_label_size = 3,                                               # Correlation and CCA plots: label size for the nodes' names
    plotCorCCA_net_method = "kamadakawai",                                   # Correlation and CCA plots: method for determining the placement of nodes in the graph (choose between: "kamadakawai" and "circle") 
    plotCorCCA_width = 13,                                                   # Correlation and CCA plots: figure dimension: width
    plotCorCCA_height = 7,                                                   # Correlation and CCA plots: figure dimension: height
    # PLOT: CORRELATION OF VARIABLES WITH CANONICAL VARIATES
    plotCCA_corr_min = 0.7,                                                  # CCA plot: threshold determining the minimum correlation to be considered between variables and canonical variates 
    plotCCA_width = 13,                                                      # CCA plot: figure dimension: width
    plotCCA_height = 7,                                                      # CCA plot: figure dimension: height
    plotCCA_max_overlaps = 1000,                                             # CCA plot: maximum number of labels that are aloud to overlap. reduce it for avoiding labels that overlap too much 
    # PLOT: ESTIMATES OF CANONICAL VARIATES (COEFFICIENTS AND CORRELATIONS)
    plotEst_width = 20,                                                      # CCA plot: figure dimension: width
    plotEst_height = 15,                                                     # CCA plot: figure dimension: height
    # PLOT: CUMULATIVE VARIANCE OF CANONICAL VARIATES
    plotCumVar_width = 20,                                                   # CCA plot: figure dimension: width
    plotCumVar_height = 10,                                                  # CCA plot: figure dimension: height
    #PLOT: CANONICAL CORRELATIONS
    plotCC_width = 20,                                                       # CCA plot: figure dimension: width
    plotCC_height = 10,                                                      # CCA plot: figure dimension: height
    # GENERIC PLOT PARAMETERS
    plots_canonical_variate = c(1, 2),                                       # The two main canonical variates chosen for plotting
    plots_group_color = "auto",                                              # Color for each group of individuals: example - suppose you have two groups, A and B, in the GROUP column, then you could define plots_group_color = c("A" = "red", "B" = "blue"). analogous for more (or less) than two groups. choose "auto" for automatic determination of colors.
    plots_x_title = "Dataset X",                                             # title describing the first dataset (data_X)
    plots_y_title = "Dataset Y",                                             # title describing the second dataset (data_Y)
    plots_short_x_title = "x",                                               # short label for the first dataset (data_X)
    plots_short_y_title = "y",                                               # short label for the second dataset (data_Y)
    plots_x_color = "green",                                                 # color for variables of the first dataset (data_X)
    plots_y_color = "blue",                                                  # color for variables of the second dataset (data_Y)
    plots_cv_color = "gold",                                                 # color for canonical variates (and their associated short label)
    plots_neg_color = "green",                                                 # color for highlighting negative correlations or negative coefficient estimates 
    plots_pos_color = "blue",                                                # color for highlighting positive correlations or positive coefficient estimates 
    plots_file_extension = "pdf",                                            # file extension for figures: "pdf" or "png"
    # DATA SPECIFICATIONS
    data_log_trans = TRUE,                                                  # log transformation for data: TRUE or FALSE
    data_log_base = 2,                                                       # log transformation for data: if data_log_trans = TRUE, choose a base for the log 
    data_sqrt_trans = FALSE,                                                 # square root transformation for data: TRUE or FALSE
    data_scale_trans = TRUE,                                                 # scale transformation for data: TRUE or FALSE (subtract mean and divide by standard deviation)
    data_X = data_X,                                                         # your first dataset (data_X): choose between an object holding your data or NA
    data_Y = data_Y,                                                         # your second dataset (data_X): choose between an object holding your data or NA                                              
    data_sheet1 = 1,                                                         # if data_X or data_Y = NA, this parameter will point to the number of a spreadsheet (corresponding to data_X) inside an Excel file that you will be asked to choose (a pop-up will show up)
    data_sheet2 = 2                                                          # if data_X or data_Y = NA, this parameter will point to the number of a spreadsheet (corresponding to data_Y) inside an Excel file that you will be asked to choose (a pop-up will show up)
  )

# CCA ---------------------------------------------------------------------------------------------------
## uncomment only one of the runCCA below and run it to start a CCA analysis

#cca <- runCCA(publish = FALSE) # run CCA using default values for parameters (list_param is not considered here)

cca <- runCCA(list_param, publish = FALSE) # run CCA using custom values for parameters (using list_param)

## choose publish = TRUE if you have already found a good set of values for list_param and achieved a CCA you consider is great for publication.
## the object 'cca' will hold the outputs of runCCA. useful if you plan to do further analysis. 